package model;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public interface IPhoto extends Serializable{
	/*
	 * Required
	 */
	
	/**
	 * @return Identifier associated with the photo.  This is normally a separate and unique identifier from filename associated with the photo.
	 */
	public String getPhotoID();
	
	/**
	 * @param id Identifier to be associated the photo.  This is normally a separate and unique identifier from filename associated with the photo.
	 */
	public void setPhotoID(String id);
	
	/*
	 * Getters and Setters
	 */
	/**
	 * @return File name associated with the photo.
	 */
	public String getFileName();
	/**
	 * @param fileName File name to be associated with the photo.  This is given by the user.
	 */
	public void setFileName(String fileName);
	/**
	 * @return Caption associated with the photo.
	 */
	public String getCaption();
	
	/**
	 * @param caption Caption to be associated with the photo.  This is given by the user.
	 */
	public void setCaption(String caption);
	/**
	 * @return Date associated with the photo.  This is generated by the application.
	 */
	public Date getDate();
	
	/**
	 * @param date Date to be associated with the photo.  This is generated by the application.  The milliseconds have been set to zero e.g. cal.set(Calendar.MILLISECOND,0);
	 */
	public void setDate(Date date);
	
	/*
	 * Tags
	 */
	
	/**
	 * 
	 * 
	 * @param tagType Tag previously added for 1-1 associations.
	 * @return Value associated with the tag.
	 */
	public <V> V getTagInjective(String tagType);
	public <V> void setTagInjective(String tagType, V value);
	public <V> List<V> getTagSurjective(String tagType);
	public <V> void setTagSurjective(List<V> value);
	
	/*
	 * Attributes
	 */
	public void setAttribute(String attributeId, String setting);
	
}
